[font]
size = 20

[font.normal]
family = "UbuntuMono Nerd Font"

[window.padding]
x = 7
y = 2

[general]
# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/github_dark.toml"]
