[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"

[window.padding]
x = 7
y = 2

[general]
# themes from https://github.com/alacritty/alacritty-theme
import = ["\\wsl$\\Ubuntu\\home\\tgroven\\.config\\alacritty\\themes\\themes\\github_dark.toml"]

[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["tmux"]